ci: update macos deployment target
Otherwise build fails with this error:

    + delocate-wheel --require-archs x86_64 -w /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/repaired_wheel -v /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/built_wheel/cpp_demangle-0.1.2-cp38-abi3-macosx_10_12_x86_64.whl
    Fixing: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/built_wheel/cpp_demangle-0.1.2-cp38-abi3-macosx_10_12_x86_64.whl
    Traceback (most recent call last):
      File "/private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/build/venv/bin/delocate-wheel", line 8, in <module>
        sys.exit(main())
      File "/private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/build/venv/lib/python3.8/site-packages/delocate/cmd/delocate_wheel.py", line 116, in main
        copied = delocate_wheel(
      File "/private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 1090, in delocate_wheel
        out_wheel_fixed = _check_and_update_wheel_name(
      File "/private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/cibw-run-4aju7ur6/cp38-macosx_x86_64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 925, in _check_and_update_wheel_name
        raise DelocationError(
    delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
    /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/tmp9i_sockf/wheel/cpp_demangle.abi3.so has a minimum target of 10.12
    Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=10.12' to update minimum supported macOS for this wheel.